{% set name = "ratingcurve" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ratingcurve-{{ version }}.tar.gz
  sha256: bc81e27fb5ce7cb7c2f1eb01daf50034ea59e9d212d480c6d991997307a5f191

build:
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - pymc >=5.0.0
    - patsy

test:
  imports:
    - ratingcurve
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ratingcurve/
  summary: A library for fitting multi-segment stage-discharge rating curves.
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thodson-usgs
